package pojo;
// Generated Oct 7, 2022 8:41:20 PM by Hibernate Tools 4.3.1

import DAO.DAOCustomer;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;




/**
 * Customer generated by hbm2java
 */
@ManagedBean
public class Customer  implements java.io.Serializable {


     private Integer idCustomer;
     private String nama;
     private String email;
     private String telp;
     private String ktp;
     private String pembayaran;
     
          public String save_user(){
         DAOCustomer add = new DAOCustomer();
         add.addCustomer(this);
         return "PaymentMessage";
     }
          
          public List<Customer> getAllRecords()
     {
         DAOCustomer usr = new DAOCustomer();
         List<Customer> lUsr = usr.retrieveCustomer();
         return lUsr;
         
     }
     
     public String getById(){
         String id_customer = idCustomer.toString();
         DAOCustomer usr = new DAOCustomer();
         List<Customer> lUsr = usr.getbyID(id_customer);
         nama = lUsr.get(0).nama;
         email = lUsr.get(0).email;
         telp = lUsr.get(0).telp;
         ktp = lUsr.get(0).ktp;
         pembayaran = lUsr.get(0).pembayaran;
         return "PaymentHistory";
     }
     
          public String edit()
     {
         DAOCustomer usr = new DAOCustomer();
         usr.editCustomer(this);
         nama = "";
         email = "";
         telp = "";
         ktp = "";
         pembayaran = "";


         FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_INFO,"Berhasil Update Data",null);
         return "PaymentHistory";
     }
     
     public String delete()
     {
         //String id_user = idUser.toString();
         DAOCustomer usr = new DAOCustomer();
         usr.deleteCustomer(idCustomer);
         nama = "";
         email = "";
         telp = "";
         ktp = "";
         pembayaran = "";

         return "PaymentHistory";
     }

    public Customer() {
    }

    public Customer(String nama, String email, String telp, String ktp) {
       this.nama = nama;
       this.email = email;
       this.telp = telp;
       this.ktp = ktp;
       this.pembayaran = pembayaran;
    }
   
    public Integer getIdCustomer() {
        return this.idCustomer;
    }
    
    public void setIdCustomer(Integer idCustomer) {
        this.idCustomer = idCustomer;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelp() {
        return this.telp;
    }
    
    public void setTelp(String telp) {
        this.telp = telp;
    }
    public String getKtp() {
        return this.ktp;
    }
    
    public void setKtp(String ktp) {
        this.ktp = ktp;
    }

    public String getPembayaran() {
        return pembayaran;
    }

    public void setPembayaran(String pembayaran) {
        this.pembayaran = pembayaran;
    }

    



}


